### ISSUE TITLE
Annotations do not evaluate for 2/3 prefixes

### ISSUE THREAD

**Issue by gbgar** [gbgar/company-bibtex#3]
I have added "annotations" and "metadata" which displays author and title, respectively for each completion candidate. This is available on the [annotations branch](https://github.com/gbgar/company-bibtex/blob/annotations/company-bibtex.el).

While completion works fine for all prefixes (@, ebib:, and the \cite{ family), annotations and metadata only work for pandoc-style (@) prefixes.

For pandoc-style citations, the author is displayed alongside each candidate (annotation), and the title of the currently-selected candidate is displayed in the echo area (meta), as expected. For the other styles, both fields display "nil".

![2016-10-22-181651_443x148_scrot](https://cloud.githubusercontent.com/assets/5402228/19623713/ee22c5ea-989a-11e6-8699-b8eacee958d9.PNG)

![2016-10-22-181802_286x154_scrot](https://cloud.githubusercontent.com/assets/5402228/19623714/f5830e9e-989a-11e6-954a-a7a2becce7d3.PNG)

When evaluating some of the functions in a scratch buffer, everything works as expected:

```
(mapcar (function(lambda(x) (company-bibtex-get-metadata x)))
(let ((prefixprefix (match-string-no-properties 1 "\cite{b")))
  (progn (mapcar (function (lambda (l) (concat prefixprefix l)))
         (mapcar (function (lambda (x) (company-bibtex-build-candidate x)))
             (company-bibtex-parse-bibliography))))))

("Blurring Boundaries: Recognizing Knowledge-Practices in the Study of Social Movements"...)
```

I suspected some sort of problem with prefix matching or with the way matches were cached after the candidates list was first calculated, but
- Changing the order of the regexes  in the `prefix` case of `company-bibtex` as well as in `company-bibtex-candidates` seems to have no effect.
- Trying a different completion prefix for the first completion after loading the backend makes no difference.

**Comment by dgutov** [comment]
The part where you `(mapcar (function (lambda (l) (concat prefixprefix l)))` is the likely culprit:

https://github.com/gbgar/company-bibtex/blob/annotations/company-bibtex.el#L107

It works for `@` prefix because it's one-character long. Which fits the first argument of the `get-text-property` calls you do later (1 means the second character in the string).

**Comment by gbgar** [comment]
@dgutov, that seems to be right. Just for testing, I changed the `get-text-property` position arguments to  `7` (after any of the prefixes would end), and this worked as expected. This is obviously not a permanent fix, but it's a start. 

Thank you very much for pointing me in the right direction!
