### ISSUE TITLE
multiple bibtex keys

### ISSUE THREAD

**Issue by rbirkelbach** [gbgar/company-bibtex#6]
Hello,

I would like to use multiple bibtex keys in a single \citep command, e.g. \citep{author1_1999, author2_2000}. I can get completes for the first citekey, but not for any further keys.
Is this already implemented and I'm just not clever enough to figure out how to do it or is this a feature that should be added in the future?

Thanks!

**Comment by gbgar** [comment]
Good catch! I use Pandoc and didn't know about the latex syntax for multiple citations, so totally not your fault.

I'll try to get it fixed this week -- PRs are always welcome, too!

**Comment by rbirkelbach** [comment]
I don't know anything about writing emacs extensions, so I sadly cannot provide input. Thanks for fixing it! 👍
